on:
  pull_request:
  push:
    branches:
      - cmake-2 

name: CI

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.4.0
      - name: make check
        run: cmake -S . -B build && cmake --build build